Cargo.toml

[Update cargo info and version]

Update cargo info and version

---

aptos-core/consensus/src/block_storage/block_tree.rs

[BugFix]: Calculate the correct prune block id to reclaim the memory usage

---

bin/gravity_node/src/consensus/mempool.rs
bin/gravity_node/src/reth_cli.rs
bin/gravity_sdk_kvstore/src/executor.rs
deploy_utils/start.sh

- Change verbose log to trace level
- Add the `log_level` parameter to the node startup script

[chore]: change verbose log to trace level

---

Cargo.toml
aptos-core/consensus/src/block_storage/block_store.rs
aptos-core/mempool/src/shared_mempool/runtime.rs
bin/bench/src/kv.rs
bin/gravity_node/src/consensus/mock.rs
bin/gravity_node/src/reth_coordinator/mod.rs
bin/gravity_sdk_kvstore/src/execution_channel.rs
bin/kvstore/src/kv.rs
crates/api-types/src/lib.rs
crates/api-types/src/mock_execution_layer.rs
crates/api/src/consensus_api.rs
rust-toolchain.toml

[feat] fix api in execution channel

---

bin/gravity_node/src/main.rs
bin/gravity_node/src/reth_coordinator/mod.rs
bin/gravity_node/src/reth_coordinator/state.rs
crates/api-types/src/lib.rs
crates/api/src/consensus_api.rs

[bugfix] Fix coredump because execute same block twice

---

bin/bench/src/kv.rs
bin/gravity_node/src/reth_coordinator/mod.rs

[fix] simplify code in bench

---

aptos-core/consensus/src/round_manager.rs
dependencies/aptos-config/src/config/quorum_store_config.rs

[feat] fix backpressure parameters

---

aptos-core/mempool/src/core_mempool/transaction_store.rs

[BugFix]: Do transaction index gc when cleaning committed transaction

---

bin/gravity_node/Cargo.toml
bin/gravity_node/src/cli.rs
bin/gravity_node/src/consensus/mock.rs
bin/gravity_node/src/main.rs
bin/gravity_node/src/reth_cli.rs
bin/gravity_node/src/reth_coordinator/mod.rs
bin/gravity_node/src/reth_coordinator/state.rs
rust-toolchain.toml

use greth after merging reth v1.2.0

feat: use greth after merging reth v1.2.0

---

aptos-core/consensus/src/block_storage/block_store.rs
aptos-core/consensus/src/counters.rs
aptos-core/consensus/src/gravity_state_computer.rs
aptos-core/consensus/src/pipeline/buffer_manager.rs
aptos-core/consensus/src/quorum_store/batch_generator.rs
aptos-core/consensus/src/quorum_store/counters.rs
aptos-core/consensus/src/quorum_store/proof_manager.rs
aptos-core/consensus/src/state_computer.rs
aptos-core/mempool/src/core_mempool/mempool.rs
aptos-core/mempool/src/counters.rs

[feat] add some aptos metric for profiling

---

aptos-core/consensus/src/block_storage/sync_manager.rs
aptos-core/consensus/src/consensusdb/mod.rs

[improve] Support to fetch block from db

---

aptos-core/consensus/src/liveness/proposer_election.rs
aptos-core/consensus/src/persistent_liveness_storage.rs
crates/api/src/consensus_mempool_handler.rs
dependencies/aptos-types/src/transaction/mod.rs

[feat] remove print in aptos

---

aptos-core/consensus/src/round_manager.rs

[feat] add env sleep var

---

.github/workflows/rust-ci.yml

[feat] add ci to build gravity node

---

Cargo.toml
aptos-core/consensus/Cargo.toml
aptos-core/consensus/src/gravity_state_computer.rs
aptos-core/consensus/src/pipeline/pipeline_builder.rs
aptos-core/consensus/src/state_computer.rs
aptos-core/mempool/Cargo.toml
aptos-core/mempool/src/shared_mempool/runtime.rs
bin/gravity_node/Cargo.toml
bin/gravity_node/src/main.rs
bin/gravity_node/src/reth_cli.rs
bin/gravity_node/src/reth_coordinator/mod.rs
crates/block-buffer-manager/Cargo.toml
crates/block-buffer-manager/src/block_buffer_manager.rs
crates/block-buffer-manager/src/lib.rs
deploy_utils/start.sh

[feat] add block buffer manager

---

aptos-core/consensus/src/block_storage/block_store.rs
dependencies/aptos-executor-types/src/lib.rs

[bugfix] Retry to fetch payload instead of panic

---

bin/gravity_node/src/reth_cli.rs
bin/gravity_node/src/reth_coordinator/mod.rs
crates/block-buffer-manager/src/block_buffer_manager.rs

[feat] fix bbm

---

aptos-core/consensus/src/consensusdb/mod.rs

At startup, need to get the block from latest_block_number-256

[bugfix] Fetch block from latest_block_number - 256

---

crates/block-buffer-manager/src/block_buffer_manager.rs

[feat] keep max persist and commit nonce

---

crates/block-buffer-manager/src/block_buffer_manager.rs

This PR adds a state management layer for the block buffer manager by introducing a new BufferState enum and integrating state checks into critical methods.
Added AtomicU8 and Ordering to support the state mechanism
Introduced a BufferState enum and a buffer_state field in BlockBufferManager
Updated several methods to check the state with an is_ready() function and panic if the state is not ready

[feat] add state

---

aptos-core/consensus/src/gravity_state_computer.rs
bin/gravity_node/src/reth_cli.rs
crates/block-buffer-manager/src/block_buffer_manager.rs
crates/block-buffer-manager/src/lib.rs

[feat] Fix some comment

---

aptos-core/consensus/src/state_computer.rs

[feat] Fix observe

---

bin/gravity_node/src/main.rs
bin/gravity_node/src/reth_cli.rs
bin/gravity_node/src/reth_coordinator/mod.rs
crates/api/src/bootstrap.rs
crates/block-buffer-manager/src/block_buffer_manager.rs

Debug recover

---

aptos-core/consensus/src/block_storage/block_store.rs
aptos-core/consensus/src/block_storage/sync_manager.rs
aptos-core/consensus/src/consensusdb/mod.rs

aptos_block_sync 0
aptos_current_block_sync_block_sum 909
aptos_recovery 0
aptos_current_recover_block_number 690

[improve] Add metric and log for recover

---

Cargo.toml
bin/gravity_node/Cargo.toml

[feat] fix build. error

---

aptos-core/consensus/src/block_storage/block_store.rs
aptos-core/consensus/src/pipeline/pipeline_builder.rs
aptos-core/consensus/src/pipeline/tests/test_utils.rs
aptos-core/consensus/src/state_computer.rs
aptos-core/consensus/src/state_computer_tests.rs
aptos-core/consensus/src/txn_notifier.rs
aptos-core/mempool/src/core_mempool/transaction.rs
aptos-core/mempool/src/core_mempool/transaction_store.rs
aptos-core/mempool/src/counters.rs
bin/gravity_node/Cargo.toml
bin/gravity_node/src/reth_cli.rs
bin/gravity_node/src/reth_coordinator/mod.rs
bin/gravity_node/src/reth_coordinator/state.rs
bin/gravity_sdk_kvstore/src/executor.rs
bin/kvstore/src/kv.rs
crates/api-types/src/compute_res.rs
crates/api-types/src/lib.rs
crates/api-types/src/mock_execution_layer.rs
dependencies/aptos-executor-types/Cargo.toml
dependencies/aptos-executor-types/src/lib.rs

[feature]: Unify the txn hash calculation logic for consensus layer and execution layer

---

.github/workflows/rust-ci.yml
aptos-core/consensus/src/state_computer.rs

[feat] call obeserve block for ordered block

---

.gitignore
aptos-core/mempool/src/core_mempool/mempool.rs
aptos-core/mempool/src/core_mempool/transaction_store.rs
aptos-core/mempool/src/shared_mempool/runtime.rs
bin/gravity_node/src/reth_cli.rs
crates/block-buffer-manager/src/block_buffer_manager.rs

This PR introduces batch transaction insertion functionality to improve mempool throughput and efficiency.
Update push_txns to drain input vectors for improved ownership handling.
Integrate new batch insertion flows in runtime, transaction_store, and mempool modules.
- [ x ] Yes

[feat] Introduces batch transaction insertion functionality to improve mempool throughput and efficiency.

---

.gitignore
deploy_utils/start.sh

[feat] add disable_compression in start.sh

---

.gitignore
Cargo.toml
bin/gravity_node/Cargo.toml
bin/gravity_node/src/consensus/mock_consensus/mock.rs
bin/gravity_node/src/main.rs

[feat] Introduces a new Cargo build profile intended for pprof support by adding a custom profile configuration in Cargo.toml

---

aptos-core/consensus/src/persistent_liveness_storage.rs
crates/api-types/Cargo.toml
crates/api-types/src/events/contract_event.rs
crates/api-types/src/events/mod.rs
crates/api-types/src/events/new_epoch.rs
crates/api-types/src/lib.rs
crates/api-types/src/on_chain_config/consensus_config.rs
crates/api-types/src/on_chain_config/mod.rs
crates/api-types/src/on_chain_config/validator_config.rs
crates/api-types/src/on_chain_config/validator_info.rs
crates/api-types/src/u256_define.rs

Export events and on chain config to api-types

---

crates/api-types/Cargo.toml
crates/api-types/src/config_storage.rs
crates/api-types/src/lib.rs

Define the ConfigStorage trait and OnChainConfig enum

---

bin/gravity_node/src/reth_cli.rs
crates/block-buffer-manager/src/block_buffer_manager.rs

[fix] fix nonce gap

---

deploy_utils/deploy.sh
deploy_utils/node1/genesis/validator.yaml
deploy_utils/node2/genesis/validator.yaml
deploy_utils/node3/genesis/validator.yaml
deploy_utils/node4/genesis/validator.yaml

[feat] set capacity_per_user 10000

---

aptos-core/mempool/src/shared_mempool/runtime.rs
bin/gravity_node/Cargo.toml
bin/gravity_node/src/consensus/mock_consensus/mock.rs
bin/gravity_node/src/reth_cli.rs
crates/block-buffer-manager/src/block_buffer_manager.rs

[feat] add gas limit in block buffer manager

---

bin/gravity_node/Cargo.toml

1. add batch insert
2. introduce grevm opt

[feat] update reth to latest

---

aptos-core/consensus/src/consensusdb/include/reader.rs

[bugfix] Fix waypoint error

---

aptos-core/consensus/src/pipeline/buffer_item.rs

[enhance]: Replace version using block number

---

aptos-core/consensus/src/test_utils/mock_storage.rs
crates/block-buffer-manager/src/block_buffer_manager.rs

[feature]: Set the parent id of the very beginning block of each epoch to the end block of the last epoch

---

aptos-core/consensus/src/consensusdb/include/reader.rs

fix: Only return ledger with epoch state in get_state_proof function

---

bin/gravity_node/Cargo.toml
bin/gravity_node/src/main.rs

Support nested hash and cache storage

---

Cargo.toml
crates/api/Cargo.toml
crates/api/src/consensus_api.rs
crates/api/src/logger.rs
crates/build-info/Cargo.toml
crates/build-info/build.rs
crates/build-info/src/lib.rs

[enhance] Use correct compile build info message

---

aptos-core/consensus/consensus-types/src/pipelined_block.rs

[fix]: use get_or_init to set exec_summary to avoid race condition

---

aptos-core/consensus/src/block_storage/sync_manager.rs
aptos-core/consensus/src/state_computer.rs

[Bugfix] Fix block sync error

---

bin/gravity_node/src/reth_cli.rs

fix: filter the same nonce txn in reth cli

---

Makefile

fix: add RUSTFLAGS="--cfg tokio_unstable" in make file

---

bin/gravity_node/Cargo.toml
deploy_utils/start.sh

fix: use bigger cache params

---

bin/gravity_node/src/consensus/mock_consensus/mempool.rs
bin/gravity_node/src/consensus/mock_consensus/mock.rs

fix: fix mock consensus

---

bin/gravity_node/src/reth_cli.rs
crates/block-buffer-manager/src/block_buffer_manager.rs

[Bugfix] Fix miss block because execute dup block number blocks

---

aptos-core/consensus/src/consensusdb/mod.rs
crates/api/src/bootstrap.rs

[improve] Support to filter when read from db

---

bin/gravity_node/src/reth_cli.rs

fix: reset pending txn if there is no txn

---

aptos-core/mempool/Cargo.toml
aptos-core/mempool/src/core_mempool/mempool.rs
aptos-core/mempool/src/core_mempool/transaction.rs
aptos-core/mempool/src/shared_mempool/runtime.rs
aptos-core/mempool/src/tests/common.rs
aptos-core/mempool/src/tests/multi_node_test.rs
aptos-core/mempool/src/tests/node.rs
aptos-core/mempool/src/tests/test_framework.rs
bin/bench/Cargo.toml
bin/bench/src/main.rs
bin/gravity_node/Cargo.toml
bin/gravity_node/src/main.rs
bin/gravity_node/src/mempool.rs
bin/gravity_node/src/reth_cli.rs
bin/gravity_node/src/reth_coordinator/mod.rs
bin/gravity_sdk_kvstore/Cargo.toml
bin/gravity_sdk_kvstore/src/main.rs
bin/kvstore/Cargo.toml
bin/kvstore/src/main.rs
crates/api/src/bootstrap.rs
crates/api/src/consensus_api.rs
crates/block-buffer-manager/Cargo.toml
crates/block-buffer-manager/src/block_buffer_manager.rs
crates/block-buffer-manager/src/lib.rs

feat: add mempool trait

---

Cargo.toml
crates/api/src/bootstrap.rs
crates/api/src/consensus_api.rs

feat: add dkg runtime
